// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_svycoxme_RCPPEXPORTS_H_GEN_
#define RCPP_svycoxme_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace svycoxme {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("svycoxme", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("svycoxme", "_svycoxme_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in svycoxme");
            }
        }
    }

    inline Rcpp::NumericVector C_rpexp(int n, Rcpp::NumericVector rate, Rcpp::NumericVector t, double start) {
        typedef SEXP(*Ptr_C_rpexp)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_C_rpexp p_C_rpexp = NULL;
        if (p_C_rpexp == NULL) {
            validateSignature("Rcpp::NumericVector(*C_rpexp)(int,Rcpp::NumericVector,Rcpp::NumericVector,double)");
            p_C_rpexp = (Ptr_C_rpexp)R_GetCCallable("svycoxme", "_svycoxme_C_rpexp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_C_rpexp(Shield<SEXP>(Rcpp::wrap(n)), Shield<SEXP>(Rcpp::wrap(rate)), Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(start)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_svycoxme_RCPPEXPORTS_H_GEN_
