# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_draw_event_times <- function(id, start_time, end_time, status, X, risk_score, baseline_hazard, baseline_hazard_start, origin, single, maximum_events = 1000L) {
    .Call(`_svycoxme_C_draw_event_times`, id, start_time, end_time, status, X, risk_score, baseline_hazard, baseline_hazard_start, origin, single, maximum_events)
}

C_rpexp <- function(n, rate, t, start) {
    .Call(`_svycoxme_C_rpexp`, n, rate, t, start)
}

agscore3 <- function(tstart, tstop, event, covar, strata, score, weights, sort1, method) {
    .Call(`_svycoxme_agscore3`, tstart, tstop, event, covar, strata, score, weights, sort1, method)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_svycoxme_RcppExport_registerCCallable`)
})
