# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_rpexp <- function(n, rate, t, start) {
    .Call(`_svycoxme_C_rpexp`, n, rate, t, start)
}

agscore3 <- function(tstart, tstop, event, covar, strata, score, weights, sort1, method) {
    .Call(`_svycoxme_agscore3`, tstart, tstop, event, covar, strata, score, weights, sort1, method)
}

coxscore2 <- function(time, status, covar, strata, score, weights, method) {
    .Call(`_svycoxme_coxscore2`, time, status, covar, strata, score, weights, method)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_svycoxme_RcppExport_registerCCallable`)
})
