# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C_draw_event_times
#'
#' Draw event times times using possibly time-varying covariate data
#'
#' @param subject_id unique identifier for subject
#'
#' @export
C_draw_event_times <- function(id, start_time, end_time, status, X, risk_score, baseline_hazard, baseline_hazard_start, origin, single, maximum_events = 1000L) {
    .Call(`_svycoxme_C_draw_event_times`, id, start_time, end_time, status, X, risk_score, baseline_hazard, baseline_hazard_start, origin, single, maximum_events)
}

#' C_rpexp
#'
#' Draw a single random number from a piecewise exponential distribution.
#' See msm::rpexp()
#'
#' @param rate vector of event rates
#' @param t vector same length as rate, giving the times the rate changes. The values of t should be ascending order.
#' @param start numeric scalar; delayed entry time. The random deviates will be left truncated.
#'
#' @export
C_rpexp <- function(n, rate, t, start) {
    .Call(`_svycoxme_C_rpexp`, n, rate, t, start)
}

#' agscore3
#'
#' Calculate score residuals for a mixed effect cox model. Only calculates for fixed effects.
#'
#' @param tstart  start time
#'	@param tstop   stop time
#'	@param event   event
#' @param strata  unique non-negative for each stratum
#' @param covar2  the matrix of covariates
#' @param score   the vector of subject scores, i.e., exp(beta*z)
#' @param weights case weights
#' @param method  ==1 for efron approx
#' @param sort1 sort order of y[,1], within strata
#' @export
agscore3 <- function(tstart, tstop, event, covar, strata, score, weights, sort1, method) {
    .Call(`_svycoxme_agscore3`, tstart, tstop, event, covar, strata, score, weights, sort1, method)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_svycoxme_RcppExport_registerCCallable`)
})
